---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
sections:
- type: heading
  label: Contenido
- type: jekyll-posts
  label: Publicaciones
  create: all
  templates:
  - post
- type: jekyll-pages
  label: Páginas
  create: all
  templates:
  - landing-page
  - default
- type: directory
  path: _people
  label: Personas
  create: all
  match: "*"
  templates:
  - person
- type: directory
  path: _projects
  label: Proyectos
  create: all
  match: "*"
  templates:
  - project
- type: document
  path: _data/information.yml
  label: Contacto
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
