---
label: Página por defecto
hide_body: true
fields:
- type: text
  name: title
  label: Título
  config:
    required: true
- type: textarea
  name: description
  label: Descripción
  description: Una pequeña descripción de la página
  config:
    required: true
- type: datetime
  name: publish_date
  label: Fecha de publicación
  config:
    required: true
- type: text
  name: layout
  label: Plantilla
  hidden: true
  default: post
