---
label: Proyecto
hide_body: false
fields:
- type: text
  name: title
  label: Título
  default: Sin título
- name: sub_heading
  label: Subtítulo
  type: text
  hidden: false
  default: ''
- name: banner_image
  label: Imagen de fondo
  type: file
  description: 'Tamaño ideal: 1200 x 400'
  hidden: false
  default: ''
- name: tags
  label: Etiquetas
  type: tag_list
  hidden: false
  default: []
- name: slug
  label: URL
  type: text
  hidden: false
  default: ''
pages:
- _projects/mandangas.md
- _projects/movidas.md
